PL/Areas/Admin/Controllers/CommentsController.cs
using BL.DTOs.CommentDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using BL.Services.Implementations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PL.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CommentsController : Controller
    {
        readonly ICommentService _commentService;
        public CommentsController(ICommentService commentService)
        {
            _commentService = commentService;
        }
        public async  Task<IActionResult> Index()
        {
            ICollection<AdminGetCommentDTO> comment = await _commentService.GetAllCommentForAdminAsync();
            return View(comment);
        }


        [HttpPost]
        public async Task<IActionResult> SoftDelete(int id)
        {
            try
            {
                await _commentService.SoftDeleteCommentAsync(id);
            }
            catch (BaseException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> HardDelete(int id)
        {
            try
            {
                await _commentService.HardDeleteCommentAsync(id);
            }
            catch (BaseException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

PL/Areas/Admin/Controllers/JobController.cs
using BL.DTOs.JobDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using CORE.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PL.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class JobController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly IJobService _jobService;
        public JobController(ICategoryService categoryService,IJobService jobService)
        {
            _categoryService = categoryService;
            _jobService = jobService;      
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                ICollection<AdminGetJobDTO> dto = await _jobService.GetJobAdminItemsAsync();
                return View(dto);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        public async Task<IActionResult> Create()
        {

            try
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                ViewData["JobNatureList"] = Enum.GetValues(typeof(JobNature))
                                .Cast<JobNature>()
                                .Select(jn => new SelectListItem
                                {
                                    Value = ((int)jn).ToString(),
                                    Text = jn.ToString()
                                }).ToList();
                return View();
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateJobDTO dto)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                ViewData["JobNatureList"] = Enum.GetValues(typeof(JobNature))
                                .Cast<JobNature>()
                                .Select(jn => new SelectListItem
                                {
                                    Value = ((int)jn).ToString(),
                                    Text = jn.ToString()
                                }).ToList();
                return View(dto);
            }

            try
            {
                await _jobService.CreateJobAsync(dto);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                ModelState.AddModelError("CustomError", ex.Message);
                return View(dto);
            }
            catch (Exception)
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                ModelState.AddModelError("CustomError", "Something went wrong!");
                return View(dto);
            }
        }

        public async Task<IActionResult> Update(int id)
        {
            try
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                return View(await _jobService.GetJobByIdForUpdateAsync(id));
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateJobDTO dto)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                return View(dto);
            }

            try
            {
                await _jobService.UpdateJobAsync(dto);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                ModelState.AddModelError("CustomError", ex.Message);
                return View(dto);
            }
            catch (Exception)
            {
                ViewData["Categories"] = new SelectList(await _categoryService.GetCategoryAdminItemsAsync(), "Id", "Title");
                ModelState.AddModelError("CustomError", "Something went wrong!");
                return View(dto);
            }
        }

        public async Task<IActionResult> SoftDelete(int id)
        {
            try
            {
                await _jobService.SoftDeleteJobAsync(id);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        public async Task<IActionResult> HardDelete(int id)
        {
            try
            {
                await _jobService.HardDeleteJobAsync(id);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                return View(await _jobService.GetJobByIdAsync(id));
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }
    }
}

PL/Areas/Admin/Controllers/UserController.cs
using BL.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PL.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IAccountService _accountService;

        public UserController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _accountService.GetAllUsersAsync();
            return View(users);
        }
    }
}

PL/Controllers/CategoryController.cs
using BL.DTOs.CategoryDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using CORE.Models;
using DATA.Contexts;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class CategoryController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly AppDbContext _appDbContext;
        public CategoryController(ICategoryService categoryService, AppDbContext appDbContext)
        {
            _categoryService = categoryService;
            _appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<HomeGetCategoryDTO> categoryDTOs=await  _categoryService.GetCategoryHomeItemsAsync();
            ICollection<Job> jobs=_appDbContext.Jobs.ToList();
            if (jobs == null)
            {
                throw new BaseException("Something went wrong");
            }
            var model = categoryDTOs.Select(category => new HomeGetCategoryDTO
            {
                Title = category.Title,
                VacancyCount = jobs.Where(job => job.CategoryId == category.Id).Sum(job => job.VacancyCount)
            }).ToList();
            return View(model);
        }
    }
}

PL/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>SB Admin 2 - Dashboard</title>
	<link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">
	<link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body id="page-top">
	<div id="wrapper">
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
			<a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
				<div class="sidebar-brand-icon rotate-n-15">
					<i class="fas fa-laugh-wink"></i>
				</div>
				<div class="sidebar-brand-text mx-3">Admin</div>
			</a>
			<a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary mt-3" style="display: block; text-align: center;">Go to Home</a>

			<li class="nav-item">
				<a class="nav-link" asp-controller="SliderItem" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>SliderItem</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Category" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Category</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Job" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Job</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="User" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Users</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" asp-controller="Comments" asp-action="Index">
					<i class="fas fa-fw fa-table"></i>
					<span>Comments</span>
				</a>
			</li>
			<hr class="sidebar-divider d-none d-md-block">
			<div class="text-center d-none d-md-inline">
				<button class="rounded-circle border-0" id="sidebarToggle"></button>
			</div>
		</ul>
		@RenderBody()
	</div>
	</div>
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>
	<!-- Bootstrap core JavaScript-->
	<script src="~/admin/vendor/jquery/jquery.min.js"></script>
	<script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Core plugin JavaScript-->
	<script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

	<!-- Custom scripts for all pages-->
	<script src="~/admin/js/sb-admin-2.min.js"></script>

	<!-- Page level plugins -->
	<script src="~/admin/vendor/chart.js/Chart.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="~/admin/js/demo/chart-area-demo.js"></script>
	<script src="~/admin/js/demo/chart-pie-demo.js"></script>

</body>

</html>