PL/Controllers/ApplyJobController.cs
using AutoMapper;
using BL.DTOs.ApplyJobDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using BL.Utilities;
using CORE.Models;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class ApplyJobController : Controller
    {
        private readonly IApplyJobService _applyJobService;
        private readonly IMapper _mapper;

        public ApplyJobController(IApplyJobService applyJobService, IMapper mapper)
        {
            _applyJobService = applyJobService;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Apply(int jobId)
        {
            var model = new CreateApplyJobDTO { JobId = jobId };
            return View(model);
        }

        
        [HttpPost]
        public async Task<IActionResult> Apply(CreateApplyJobDTO dto)
        {
            if (!ModelState.IsValid)
                return View(dto);

            try
            {
                string cvFilename = await dto.CV.SaveAsync("CVs");

                ApplyJob applyJob = _mapper.Map<ApplyJob>(dto);
                applyJob.CV = cvFilename; 

                await _applyJobService.SendEmailAsync(applyJob, cvFilename);


                TempData["Success"] = "Müraciətiniz uğurla göndərildi!";
                return RedirectToAction("Index", "Job", new { id = dto.JobId });
            }
            catch (BaseException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(dto);
            }
        }

















        // ✅ Müəyyən bir işin müraciətlərini silmək üçün
        [HttpPost]
        public async Task<IActionResult> DeleteApplications(int jobId)
        {
            try
            {
                await _applyJobService.DeleteApplicationsByJobIdAsync(jobId);
                TempData["Success"] = "Müraciətlər uğurla silindi!";
            }
            catch (BaseException ex)
            {
                TempData["Error"] = ex.Message;
            }
            return RedirectToAction("JobApplications", new { jobId });
        }










        // ✅ Müəyyən bir işə edilən bütün müraciətləri göstərir (Admin Panel üçün)
        [HttpGet]
        public async Task<IActionResult> JobApplications(int jobId)
        {
            try
            {
                var applications = await _applyJobService.GetApplicationsByJobIdAsync(jobId);
                return View(applications);
            }
            catch (BaseException ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Index", "Job");
            }
        }
    }
}

PL/Controllers/JobDetailsController.cs
using AutoMapper;
using BL.DTOs.ApplyJobDTOs;
using BL.DTOs.JobDTOs;
using BL.Services.Abstractions;
using BL.Utilities;
using CORE.Enums;
using CORE.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace PL.Controllers
{
    public class JobDetailsController : Controller
    {
        readonly IJobService _jobService;
        readonly IMapper _mapper;
        readonly IApplyJobService _applyJobService;
        public JobDetailsController(IJobService jobService, IMapper mapper, IApplyJobService applyJobService)
        {
            _jobService = jobService;
            _mapper = mapper;
            _applyJobService = applyJobService;
        }
        public async Task<IActionResult> Index(int id)
        {
            try
            {
                Job? job = await _jobService.GetJobByIdAsync(id);
                JobDetailDTO detailDTO = _mapper.Map<JobDetailDTO>(job);
                ViewData["JobNatureList"] = Enum.GetValues(typeof(JobNature))
                .Cast<JobNature>()
                .Select(jobN => new SelectListItem
                {
                    Value = ((int)jobN).ToString(),
                    Text = jobN.ToString()
                }).ToList();
                return View(detailDTO);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }
    }
}

PL/Controllers/JobListController.cs
using BL.DTOs.JobDTOs;
using BL.Services.Abstractions;
using CORE.Enums;
using CORE.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PL.Controllers
{
    public class JobListController : Controller
    {
        readonly IJobService _jobService;
        public JobListController(IJobService jobService)
        {
            _jobService = jobService;          
        }
        public async Task<IActionResult> Index(bool showAllAll = false, bool showAllFullTime = false, bool showAllPartTime = false)
        {
            try
            {
                ICollection<JobListDTO> dto = await _jobService.GetJobForListViewAsync();

                var allJobs = dto.ToList();
                ViewBag.TotalAllJobs = allJobs.Count;
                ViewBag.ShowAllAll = showAllAll;
                if (!showAllAll) allJobs = allJobs.Take(5).ToList();


                var fullTimeJobs = dto.Where(j => j.JobNature.ToString() == "FullTime").ToList();
                ViewBag.TotalFullTimeJobs = fullTimeJobs.Count;
                ViewBag.ShowAllFullTime = showAllFullTime;
                if (!showAllFullTime) fullTimeJobs = fullTimeJobs.Take(5).ToList();


                var partTimeJobs = dto.Where(j => j.JobNature.ToString() == "PartTime").ToList();
                ViewBag.TotalPartTimeJobs = partTimeJobs.Count;
                ViewBag.ShowAllPartTime = showAllPartTime;
                if (!showAllPartTime) partTimeJobs = partTimeJobs.Take(5).ToList();

                ViewBag.AllJobs = allJobs;
                ViewBag.FullTimeJobs = fullTimeJobs;
                ViewBag.PartTimeJobs = partTimeJobs;

                ViewData["JobNatureList"] = Enum.GetValues(typeof(JobNature))
                .Cast<JobNature>()
                .Select(jobN => new SelectListItem
                {
                    Value = ((int)jobN).ToString(),
                    Text = jobN.ToString()
                }).ToList();

                return View(dto);
            }
            catch (Exception) 
            {
                return BadRequest("Something went wrong!");
            }
        }
    }
}

PL/Views/JobList/Index.cshtml
@{
	var allJobs = ViewBag.AllJobs as List<JobListDTO>;
	var fullTimeJobs = ViewBag.FullTimeJobs as List<JobListDTO>;
	var partTimeJobs = ViewBag.PartTimeJobs as List<JobListDTO>;
}

<div class="container-xxl py-5">
	<div class="container">
		<h1 class="text-center mb-5">Job Listing</h1>
		<div class="tab-class text-center">
			<ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
				<li class="nav-item">
					<a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-1">
						<h6 class="mt-n1 mb-0">All</h6>
					</a>
				</li>
				<li class="nav-item">
					<a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
						<h6 class="mt-n1 mb-0">Full Time</h6>
					</a>
				</li>
				<li class="nav-item">
					<a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
						<h6 class="mt-n1 mb-0">Part Time</h6>
					</a>
				</li>
			</ul>
			<div class="tab-content">
				<!-- All Jobs  -->
				<div id="tab-1" class="tab-pane fade show active p-0">
					@foreach (var item in allJobs)
					{
						<partial name="_JobItemPartial" model="item" />
					}
					@if (!ViewBag.ShowAllAll && ViewBag.TotalAllJobs > 5)
					{
						<a class="btn btn-primary py-3 px-5" asp-action="Index" asp-route-showAllAll="true">Browse More Jobs</a>
					}
				</div>

				<!-- FullTime Jobs  -->
				<div id="tab-2" class="tab-pane fade show p-0">
					@foreach (var item in fullTimeJobs)
					{
						<partial name="_JobItemPartial" model="item" />
					}
					@if (!ViewBag.ShowAllFullTime && ViewBag.TotalFullTimeJobs > 5)
					{
						<a class="btn btn-primary py-3 px-5" asp-action="Index" asp-route-showAllFullTime="true">Browse More Jobs</a>
					}
				</div>

				<!-- PartTime Jobs  -->
				<div id="tab-3" class="tab-pane fade show p-0">
					@foreach (var item in partTimeJobs)
					{
						<partial name="_JobItemPartial" model="item" />
					}
					@if (!ViewBag.ShowAllPartTime && ViewBag.TotalPartTimeJobs > 5)
					{
						<a class="btn btn-primary py-3 px-5" asp-action="Index" asp-route-showAllPartTime="true">Browse More Jobs</a>
					}
				</div>
			</div>
		</div>
	</div>
</div>

PL/Views/JobList/_JobItemPartial.cshtml
@model JobListDTO
@if(Model.IsDeleted==false)
{
    <div class="job-item p-4 mb-4">
        <div class="row g-4">
            <div class="col-sm-12 col-md-8 d-flex align-items-center">
                <img class="flex-shrink-0 img-fluid border rounded" src="~/Uploads/Jobs/@Model.CompanyIconPath" alt="" style="width: 80px; height: 80px;">
                <div class="text-start ps-4">
                    <h5 class="mb-3">@Model.Title</h5>
                    <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>@Model.Location</span>
                    <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>@Model.JobNature.ToString()</span>
                    <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$@Model.MinSalary  - $@Model.MaxSalary</span>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                <div class="d-flex mb-3">
                    <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                    <a class="btn btn-primary" asp-controller="JobDetails" asp-action="Index" asp-route-id="@Model.Id">Detail</a>
                    <a class="btn btn-primary" asp-controller="ApplyJob" asp-action="Apply" asp-route-jobId="@Model.Id">Apply now</a>
                </div>
                <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: @Model.DateLine</small>
            </div>
        </div>
    </div>
}