PL/Areas/Admin/Controllers/SliderItemController.cs
using AutoMapper;
using BL.DTOs.SliderItemDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PL.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SliderItemController : Controller
    {
        readonly ISliderItemService _sliderItemService;
        readonly IMapper _mapper;
        public SliderItemController(ISliderItemService sliderItemService,IMapper mapper)
        {
            _sliderItemService = sliderItemService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                ICollection<GetSliderItemDTO> dto = await _sliderItemService.GetAllSliderItemAsync();
                return View(dto);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong");
            }
        }
        public  IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSliderItemDTO dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            try
            {
                await _sliderItemService.CreateSliderItemAsync(dto);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                ModelState.AddModelError("CustomError", ex.Message);
                return View(dto);
            }
            catch (Exception)
            {
                ModelState.AddModelError("CustomError", "Something went wrong!");
                return View(dto);
            }
        }

        public async Task<IActionResult> Update(int id)
        {
            try
            {
                var sliderItem = await _sliderItemService.GetSliderItemByIdAsync(id);
                UpdateSliderItemDTO updateDto = _mapper.Map<UpdateSliderItemDTO>(sliderItem);
                return View(updateDto);
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateSliderItemDTO dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            try
            {
                await _sliderItemService.UpdateSliderItemAsync(dto);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                ModelState.AddModelError("CustomError", ex.Message);
                return View(dto);
            }
            catch (Exception)
            {
                ModelState.AddModelError("CustomError", "Something went wrong!");
                return View(dto);
            }
        }
        public async Task<IActionResult> SoftDelete(int id)
        {
            try
            {
                await _sliderItemService.SoftDeleteSliderItemAsync(id);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }


        public async Task<IActionResult> HardDelete(int id)
        {
            try
            {
                await _sliderItemService.HardDeleteSliderItemAsync(id);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                return View(await _sliderItemService.GetSliderItemByIdAsync(id));
            }
            catch (BaseException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }
    }
}

PL/Areas/Admin/Views/SliderItem/Create.cshtml
@model CreateSliderItemDTO
<div class="container-fluid d-flex justify-content-center align-items-center min-vh-100">
    <div class="row w-100">
        <div class="col-md-8 mx-auto">
            <div class="card shadow-lg rounded">
                <div class="card-body">
                    <h4 class="text-primary text-center">Create Slider Item</h4>
                    <form method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label class="font-weight-bold">Title</label>
                            <input asp-for="Title" type="text" class="form-control border-primary" placeholder="Title">
                            <span class="text-danger" asp-validation-for="Title"></span>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">Description</label>
                            <input asp-for="Description" type="text" class="form-control border-primary" placeholder="Description">
                            <span class="text-danger" asp-validation-for="Description"></span>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">Image</label>
                            <input asp-for="Image" type="file" class="form-control border-primary p-2">
                            <span class="text-danger" asp-validation-for="Image"></span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a class="btn btn-outline-secondary" asp-controller="SliderItem" asp-action="Index">Cancel</a>
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

PL/Areas/Admin/Views/SliderItem/Index.cshtml
@model ICollection<GetSliderItemDTO>
@{
    string disabled = string.Empty;
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Slider Items Table</h4>
                        <p class="card-description">
                            <a asp-action="Create" class="btn btn-success btn-sm">
                                <i class="fas fa-plus"></i> Create
                            </a>
                        </p>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Image</th>
                                        <th style="max-width: 150px;">Title</th>
                                        <th style="max-width: 250px;">Description</th>
                                        <th>Is Deleted</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (GetSliderItemDTO item in Model)
                                    {
                                        disabled = (item.IsDeleted) ? "disabled" : string.Empty;
                                        <tr>
                                            <td class="py-1">@item.Id</td>
                                            <td>
                                                <img style="object-fit: cover; width: 100px; height: 60px;"
                                                     src="~/Uploads/SliderItems/@item.ImgPath" alt="Inner Image" />
                                            </td>
                                            <td class="text-break" style="word-wrap: break-word; white-space: normal; max-width: 150px;">
                                                @item.Title
                                            </td>
                                            <td class="text-break" style="word-wrap: break-word; white-space: normal; max-width: 250px;">
                                                @item.Description
                                            </td>
                                            <td>@item.IsDeleted</td>
                                            <td style="white-space: nowrap;">
                                                <a class="btn btn-warning btn-sm d-inline-block mx-1 text-white" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                                <a class="btn btn-danger btn-sm d-inline-block mx-1 @disabled" asp-action="SoftDelete" asp-route-id="@item.Id">SoftDelete</a>
                                                <a class="btn btn-danger btn-sm d-inline-block mx-1" asp-action="HardDelete" asp-route-id="@item.Id">HardDelete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PL/Areas/Admin/Views/SliderItem/Update.cshtml
@model UpdateSliderItemDTO;
<div class="container-fluid d-flex justify-content-center align-items-center min-vh-100">
    <div class="row w-100">
        <div class="col-md-8 mx-auto">
            <div class="card shadow-lg rounded">
                <div class="card-body">
                    <h4 class="text-primary text-center">Update Slider Item</h4>
                    <form method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label class="font-weight-bold">Id</label>
                            <input asp-for="Id" type="text" class="form-control border-primary" placeholder="Id">
                            <span class="text-danger" asp-validation-for="Id"></span>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">Title</label>
                            <input asp-for="Title" type="text" class="form-control border-primary" placeholder="Title">
                            <span class="text-danger" asp-validation-for="Title"></span>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">Description</label>
                            <input asp-for="Description" type="text" class="form-control border-primary" placeholder="Description">
                            <span class="text-danger" asp-validation-for="Description"></span>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold">Image</label>
                            <input asp-for="Image" type="file" class="form-control border-primary p-2">
                            <span class="text-danger" asp-validation-for="Image"></span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <a class="btn btn-outline-secondary" asp-controller="SliderItem" asp-action="Index">Cancel</a>
                            <button  type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>