PL/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PL/Controllers/CategoryController.cs
using BL.DTOs.CategoryDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using CORE.Models;
using DATA.Contexts;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class CategoryController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly AppDbContext _appDbContext;
        public CategoryController(ICategoryService categoryService, AppDbContext appDbContext)
        {
            _categoryService = categoryService;
            _appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<HomeGetCategoryDTO> categoryDTOs=await  _categoryService.GetCategoryHomeItemsAsync();
            ICollection<Job> jobs=_appDbContext.Jobs.ToList();
            if (jobs == null)
            {
                throw new BaseException("Something went wrong");
            }
            var model = categoryDTOs.Select(category => new HomeGetCategoryDTO
            {
                Title = category.Title,
                VacancyCount = jobs.Where(job => job.CategoryId == category.Id).Sum(job => job.VacancyCount)
            }).ToList();
            return View(model);
        }
    }
}

PL/Controllers/JobListController.cs
using BL.DTOs.JobDTOs;
using BL.Services.Abstractions;
using CORE.Enums;
using CORE.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PL.Controllers
{
    public class JobListController : Controller
    {
        readonly IJobService _jobService;
        public JobListController(IJobService jobService)
        {
            _jobService = jobService;          
        }
        public async Task<IActionResult> Index(bool showAllAll = false, bool showAllFullTime = false, bool showAllPartTime = false)
        {
            try
            {
                ICollection<JobListDTO> dto = await _jobService.GetJobForListViewAsync();

                var allJobs = dto.ToList();
                ViewBag.TotalAllJobs = allJobs.Count;
                ViewBag.ShowAllAll = showAllAll;
                if (!showAllAll) allJobs = allJobs.Take(5).ToList();


                var fullTimeJobs = dto.Where(j => j.JobNature.ToString() == "FullTime").ToList();
                ViewBag.TotalFullTimeJobs = fullTimeJobs.Count;
                ViewBag.ShowAllFullTime = showAllFullTime;
                if (!showAllFullTime) fullTimeJobs = fullTimeJobs.Take(5).ToList();


                var partTimeJobs = dto.Where(j => j.JobNature.ToString() == "PartTime").ToList();
                ViewBag.TotalPartTimeJobs = partTimeJobs.Count;
                ViewBag.ShowAllPartTime = showAllPartTime;
                if (!showAllPartTime) partTimeJobs = partTimeJobs.Take(5).ToList();

                ViewBag.AllJobs = allJobs;
                ViewBag.FullTimeJobs = fullTimeJobs;
                ViewBag.PartTimeJobs = partTimeJobs;

                ViewData["JobNatureList"] = Enum.GetValues(typeof(JobNature))
                .Cast<JobNature>()
                .Select(jobN => new SelectListItem
                {
                    Value = ((int)jobN).ToString(),
                    Text = jobN.ToString()
                }).ToList();

                return View(dto);
            }
            catch (Exception) 
            {
                return BadRequest("Something went wrong!");
            }
        }
    }
}

PL/Controllers/TestimonialController.cs
using System.Security.Claims;
using BL.DTOs.CommentDTOs;
using BL.Exceptions;
using BL.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace PL.Controllers
{
    public class TestimonialController : Controller
    {

        readonly ICommentService _commentService;
        readonly IAccountService _accountService;

        public TestimonialController(ICommentService commentService, IAccountService accountService)
        {
            _commentService = commentService;
            _accountService = accountService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                ICollection<GetCommentDTO> dto = await _commentService.GetAllCommentForViewAsync();               
                return View(dto);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }

        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Create(CreateCommentDTO dto)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (userId == null)
                {
                    return Unauthorized(new { success = false, message = "User is not logged in. You must LOGIN first" });
                }
                await _commentService.CreateCommentAsync(dto, userId);
                return RedirectToAction("Index");
            }
            catch (BaseException ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
            catch (Exception)
            {
                return StatusCode(500, new { success = false, message = "An unexpected error occurred." });
            }
        }

    }
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JobEntry - Job Portal Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <div class="container-xxl bg-white p-0">
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a href="index.html" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
                <h1 class="m-0 text-primary">JobEntry</h1>
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Home</a>
                    <a asp-controller="About" asp-action="Index" class="nav-item nav-link">About</a>
                    <a asp-controller="JobList" asp-action="Index" class="nav-item nav-link">Job</a>
                    <a asp-controller="Category" asp-action="Index" class="nav-item nav-link">Category</a>
                    <a asp-controller="Testimonial" asp-action="Index" class="nav-item nav-link">Testimonial</a>
                    <a asp-controller="Account" asp-action="Index" class="nav-item nav-link "
                       style="width: 45px; height: 45px;  font-size: 18px; ">
                        👤
                    </a>
                </div>
                <a href="" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        @RenderBody()
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-12 col-md-12 text-center">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA | <i class="fa fa-phone-alt me-3"></i>+012 345 67890 | <i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex justify-content-center pt-2">
                            <a class="btn btn-outline-light btn-social mx-1" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social mx-1" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
</body>
</html>